winpython/winpython

- make.py
- portable/launcher.nsi
- winpython/data/packages.ini
- winpython/data/tools.ini
- winpython/utils.py
- winpython/wppm.py
Support the wheel binary formats when building winpython
Don't use absolute path when creating a package .exe launcher
> Accept binary wheels, patch standard pip package

- make.py
- setup.cfg
- setup.py
- winpython/__init__.py
- winpython/utils.py
Winpython can now rely only on the wheel package format.
> A complete tour of wheel

- make.py
- portable/launcher.nsi
- winpython/utils.py
- winpython/wppm.py
finishing the wheel transition
> pre-install pip via get-pip or ensurepip

- make.py
- winpython/data/packages.ini
Wheel format can so resolve inter-dependancies
> Building Winpython with all packages in one directory

- make.py
- winpython/data/packages.ini
we copy everything to the wheeldir directory at the beginning of the process.
> remove multiple package directories handling during build

- make.py
adjust to IPython3.0 notebook that now shows everything in a directory
> move docs to winpython\notebooks\docs 

- make.py
- portable/launcher.nsi
- winpython/data/packages.ini
- winpython/utils.py
- winpython/wppm.py
> Various fixes to improve Python and Julia portability

- winpython/wppm.py
solves https://github.com/winpython/winpython/issues/63
> WPPM shows all pip-installed packages

- winpython/wppm.py
by default, pip can't refresh it's package list
> a refreshed pip

- winpython/data/packages.ini
(one day I should try get it automatically)
> update package list

- make.py
Changed to adapt to spyder 2.3.5.
> 'spyder launcher' icons now rely on 'spyder.exe'

- make.py
as suggested by Christoph Gohlke.
> launch spyder the direct way

- diff.py
- make.py
to be compatible with coming requirements.txt installation method
> do changelog via pip freeze

- make.py
- winpython/data/packages.ini
- winpython/utils.py
- winpython/wppm.py
allow using 'pip -r` in the intermediate `run_complement.bat` step
> be compatible with requirement.txt usage

- winpython/wppm.py
(better place than current run_complement.bat)
> workaround bad installers inside wppm

- make.py
Fix missing environment variables.
> fix cython use vc script

- winpython/wppm.py
should help  'pip uninstall' and 'pip upgrade'
> improves usage of pip in WinPython

- make.py
- winpython/utils.py
- winpython/wppm.py
maybe not a good idea, but not sure of the bad side effect, and visible good effects
> shebang "..\python.exe" vs "python.exe"

- make.py
- winpython/__init__.py
(a small step in that direction)
> simplify build system

- make.py
> spyder has changed of launching method

- make.py
a step in the direction of using something simpler than NSIS
https://github.com/winpython/winpython/issues/286
> shimmy compatibility fix

- make.py
> remove spyder(reset) icon

- make.py
should help splitting build process
> more pre-defined Build directories

- diff.py
- generate_a_winpython_distro.bat
- make.py
- winpython/utils.py
rootdir is no more use.
basedir and CHANGELOGS_DIR are used instead.
> build simplification

- winpython/wppm.py
this pyuic4 works withing normal command prompt (and not only from the "WinPython Command Prompt")
I also modified the script pyuic5.bat (even if I could not test)
> modification of pyuic4.bat (see #299)

- make.py
> "spyder reset" icon is back

- make.py
> Updated env.bat script to not modify %path% if %WINPYDIR% already exists

- make.py
fixes https://github.com/winpython/winpython/issues/314
> work again with spaces in path

- make.py
solve an issue related to https://github.com/winpython/winpython/issues/315
> preserve "python" standard behavior

- make.py
solve issue https://github.com/winpython/winpython/issues/322
> survive better to space

- winpython/wppm.py
solves https://github.com/winpython/winpython/issues/330
> don't use pip internal API

- make.py
> powershell console step2

- make.py
fix for https://github.com/winpython/winpython/issues/384
> python.bat shall not change directory

- make.py
fix for https://github.com/winpython/winpython/issues/432
thanks to @georgejean
> powershell launcher fix

- make.py
https://github.com/winpython/winpython/issues/436
> @georgejean tweaks for powershell

- make.py
as directory may be empty. solves side-effect of https://github.com/winpython/winpython/issues/449
> better check PyQt5

- winpython/wppm.py
solves https://github.com/winpython/winpython/issues/454
> don't let the hexawheels get you down

- winpython/data/packages.ini
- winpython/wppm.py
suppose to improve on https://github.com/winpython/winpython/issues/467
> better management of  wheel names (take3)

- README.rst
Added description so that user will not be confused with WinPython-x.x.x.-Zero package setup.
#397  #401
> requirements updated for user guidance

- winpython/qt/__init__.py
should fix https://github.com/winpython/winpython/issues/483
> try to improve PyQt4 downgrade

- winpython/wppm.py
fix https://github.com/winpython/winpython/issues/470
> use https in relase documents, no more http

- make.py
spyder.exe is now spyder3.exe
see https://github.com/winpython/winpython/issues/489
> adapt to spyder-3.1.3+

- make.py
fix for https://github.com/winpython/winpython/issues/494
> desactivate python._pth  for Python-3.6

- make.py
- winpython/data/packages.ini
workaround mysterious Neard behavior: https://github.com/winpython/winpython/issues/500
> compatiblity tweak for Neard users

- make.py
solves https://github.com/winpython/winpython/issues/530
> Jupyter Lab icon (to make users testing easy)

- make.py
to help on https://github.com/winpython/winpython/issues/502
> pyqt5-tools compatibility

- make.py
so it's createed in build process
> move pyzo setup in the initialization place

- winpython/data/packages.ini
https://github.com/winpython/winpython/pull/654
thanks to @CAM-Gerlach for clean-up call
> giant cleanup to get clother to pip

- portable/installer.nsi
- portable/installer_INNO.iss
> include the 32/64 type in the suggested install path

- make.py
solves https://github.com/winpython/winpython/issues/716
> support installation on PC with ampersand (&) in their %PATH%

- make.py
> further cleanup of legacy method

- hash.py
a first experiment at black, on one small file 
https://github.com/winpython/winpython/issues/751
> have hash.py tuned per  'black' formatter

- winpython/associate.py
- winpython/config.py
- winpython/controlpanel.py
https://github.com/winpython/winpython/issues/751
> black associate.py, config.py, controlpanel.py

- winpython/data/packages.ini
... may need a way to automate this one day
> package names

- winpython/__init__.py
- winpython/data/packages.ini
exceptionnaly palyndromic comit, only every 909 years. 02022020
as said Lex Fridman, we need more love and commitments, to fight the dark forces.
> new package names

- winpython/__init__.py
- winpython/data/packages.ini
- winpython/disthelpers.py
- winpython/py3compat.py
solves https://github.com/winpython/winpython/issues/807
> python-3.9 compatibility

- make.py
- winpython/__init__.py
solves https://github.com/winpython/winpython/issues/813
> tweak env.bat

- winpython/wppm.py
go try fetch the information from pypi
put '**' in front of package summary coming live from pypi
> remove the need to update package.ini step2

- diff.py
- make.py
- winpython/__init__.py
- winpython/data/packages.ini
- winpython/wppm.py
solves https://github.com/winpython/winpython/issues/827
- packages.ini initially empty (or made of normalized name packages)
- during build new package names are added from pypi when needed.
> auto-update of packages.ini at build time

- winpython/__init__.py
- winpython/data/packages.ini
- winpython/utils.py
- winpython/wppm.py
> modernize utils

- winpython/disthelpers.py
see https://github.com/winpython/winpython/issues/828
> dll issue mitigation

- make.py
- winpython/__init__.py
solves https://github.com/winpython/winpython/issues/839
> python-3.8 and 3.9 don't use HOME anymore to get user settings, but USERPROFILE

- make.py
https://github.com/winpython/winpython/issues/839
> further tweak on USERPROFILE

- make.py
https://github.com/winpython/winpython/issues/899
> resolve the ampersand character problem

- make.py
see https://github.com/winpython/winpython/issues/898
> don't force "notebook" directory on VScode icon

- generate_a_winpython_distro.bat
- run_complement_newbuild.bat
> Jupyterlab2 farewell and pip --log audit addition

- make.py
- winpython/__init__.py
Drag&Drop of a python file on idle and spyder and jupyterlab icons shall open the file with the workingDir on the file's directory
> trying to open in the "desired" directory for idle/spyder/jupyter

- run_complement_newbuild.bat
https://github.com/krassowski/jupyterlab-lsp/pull/580
> force utf-8 in jupyter_lsp-1.1.4

- winpython/__init__.py
- winpython/data/packages.ini
- winpython/utils.py
should solve https://github.com/winpython/winpython/issues/978
> better support utf-8

- make.py
- winpython/__init__.py
- winpython/utils.py
solves https://github.com/winpython/winpython/issues/1012
> tweak PyPy-3.7 launchers

- winpython/__init__.py
- winpython/wppm.py
fix https://github.com/winpython/winpython/issues/1017
> pip-21.3 deprecates get_installed_distributions

- make.py
- winpython/__init__.py
to help on https://github.com/winpython/winpython/issues/1038
> reduce default path length

- make.py
https://github.com/winpython/winpython/pull/1024
> re-apply  patch #1024

- make.py
try to fix https://github.com/winpython/winpython/issues/1039
> another workaround on DOS

- make.py
... trying not to get mad at DOS
> DOS housekeeping

- make.py
resolves https://github.com/winpython/winpython/issues/1096
> make inno setup not mandatory

- make.py
https://github.com/winpython/winpython/issues/1097
> fix Windows Terminal icon behavior

- make.py
use wppm -p and wppm -r instead
> remove pipdeptree patch

- winpython/__init__.py
- winpython/piptree.py
surviving toml in "wppm -p fastapi" example
> one re.split to split them all

- run_complement_newbuild.bat
https://github.com/winpython/winpython/issues/1121
> patching live cpython-3.10.8 IDLE

- generate_a_winpython_distro.bat
- make.py
dust can cause hard to understand effect
> hunt and remove historic build practice

- winpython/controlpanel.py
https://github.com/winpython/winpython/issues/1141
> Fix broken ControlPanel

- winpython/wppm.py
while checking and removing osp comments
> fix (Path(scriptpy) / name).is_file()

- make.py
while cheking and removing osp comments
> add a resolve()  for portable_dir

- README.rst
python rst2html.py --strict README.rst
> a README.rst that docutils tolerates

- winpython/data/packages.ini
> pymc package names

- winpython/data/packages.ini
- winpython/piptree.py
example: wppm -r dask[complete] , wppm -r dask[array,test]
> better display package dependencies

- changelogs/WinPython-64bit-3.10.11.1.md
- changelogs/WinPython-64bit-3.10.11.1_History.md
- changelogs/WinPython-64bit-3.11.3.1.md
- changelogs/WinPython-64bit-3.11.3.1_History.md
- changelogs/WinPythondot-32bit-3.10.11.1.md
- changelogs/WinPythondot-32bit-3.10.11.1_History.md
- changelogs/WinPythondot-64bit-3.10.11.1.md
- changelogs/WinPythondot-64bit-3.10.11.1_History.md
- changelogs/WinPythondot-64bit-3.11.3.1.md
- changelogs/WinPythondot-64bit-3.11.3.1_History.md
- changelogs/md5_sha1.txt
- winpython/__init__.py
- winpython/qthelpers.py
From WinPython-2023-01:
- fix a onliner preventing the WinPython Control Panel to open
- upgrade to toolz-0.12.0  for python-3.11 compatibility
> WinPython 2023-01 post1

- winpython/associate.py
one entry per WinPython-Major.Minor version
becoming VSCode visible
> PEP-514 at last

- winpython/__init__.py
- winpython/piptree.py
- winpython/wppm.py
trying to be more practical than METADATA or pip inspect
> add wppm -lsa -v

- make.py
- winpython/__init__.py
- winpython/wppm.py
> control Panel removed, icon will launch wppm help instead

- winpython/piptree.py
- winpython/wppm.py
> speed-up wppm in the common case

- winpython/__init__.py
- winpython/wppm.py
> pip search is gone

- winpython/piptree.py
> get rid of pip inspect

- winpython/__init__.py
- winpython/piptree.py
- winpython/wppm.py
and by so, drop support for Python-3.7 and below
> remove dependance on pip command line

- make.py
WinPython dot on python-3.8, and flit package
> simplify Python build requirement

- winpython/utils.py
> remove no more used code

- winpython/piptree.py
'.' is for all packages or all extras
> support wppm -p .[.]  and wppm -r .

- winpython/__init__.py
- winpython/piptree.py
> squash bugs on wppm -r

- winpython/piptree.py
wppm -r not working for langchain <- numpy
> piptree upward improvment

- make.py
and simplify to one single place of specification
> move winpython.ini changes from .bat to .py

- portable/launchers_src/LICENSE
- portable/launchers_src/build_one_launcher.bat
- portable/launchers_src/launcher_template_CONSOLE.cpp
- portable/launchers_src/launcher_template_WINDOWS.cpp
by WinPython Creator Pierre Raybaut @PierreRaybaut
> adding the new launcher technology proposed per Datalab

- winpython/piptree.py
- winpython/wppm.py
note gpt4o  doesn't propose typing... one thing at a time
> simplify using copilote/gpt4o

- winpython/piptree.py
has to do manualy otherwise suprises...
> simplify piptree using copilote-gpt4o

- winpython/piptree.py
still it did propose bad simplifications or unwanted code removal. so need to be carefull in this transition
> simplify piptree with gemini flash help

- winpython/utils.py
GRok doesn't rewrite the full file... geminy is more kind
> improve utils.py code with grok

- winpython/piptree.py
again, with IA of march 2025:
- some details are not right, like the "strip" vs "translate",
- some other details are good suggestions
- ... a code not safely managed per IA is a burden of maintainance
> improve piptree.py via IA + manual check

- make.py
back to initial length of make.py
> further cosmetic clean-up

- winpython/associate.py
shall fix https://github.com/winpython/winpython/issues/1576
(for this rc at least)
> a bug at rc

- winpython/wppm.py
> fix changelog loosing its package description

- portable/launchers_src/launcher_template_WINDOWS.cpp
Fixes #1564 for window launchers, by implementing #1569.
> Forward command line arguments for window launchers

- winpython/wppm.py
from winpython import wppm;print(wppm.Distribution().generate_package_index_markdown())
> wppm can auto-report

- winpython/packagemetadata.py
- winpython/piptree.py
- winpython/wppm.py
navigating into a WheelHouse..
> wppm -ls -ws ... works

- portable/scripts/WinPython_PS_Prompt.ps1
Fixes https://github.com/winpython/winpython/issues/1649 by removing calls which might be unwarranted.
> Remove console colorization from WinPython_PS_Prompt.ps1

- portable/launchers_final/scripts/WinPythonIni.py
- portable/launchers_final/scripts/env.bat
should resolve https://github.com/winpython/winpython/issues/1651
> get spyder config directory portable

- .github/workflows/github_workflows_build-dot.yml
we note copilote pushes for powershell, but that's not a problem
> prepare for build #5

- .github/workflows/github_workflows_build-dot.yml
fascinating/educating to see AI influencing itself
> revert to curl from build #5 failure
